[package]
name = "rchc"
version = "0.1.0"
authors = ["Timoth√©e Haudebourg <timothee.haudebourg@irisa.fr>"]
edition = "2018"

[dependencies]
log = "*"
stderrlog = "*"
clap = { version = "~2.27.0", features = ["yaml"] }
rand = "*"
utf8-decode = "*"
source-span = "*"
const-vec = "*"
once_cell = "*"
smt2 = "*"
terms = "*"
tree-automata = "*"
automatic-relations = "*"
crossbeam-channel = "*"
crossbeam-utils = "*"
rust-embed = "*"
